export const footer1Data = [
  {
    id: 1,
    heading: "Gifts by Recipient :",
    links: ["Gifts for Her", "Gifts for Him", "Gifts for Couples"],
  },
  {
    id: 2,
    heading: "Gifts by Relationship :",
    links: [
      "Gifts for Husband",
      "Gifts for Wife",
      "Gifts for Boyfriend",
      "Gifts for Girlfriend",
      "Gifts for Father",
      "Gifts for Mother",
      "Gifts for Son",
      "Gifts for Daughter",
      "Gifts for Brother",
    ],
  },
  {
    id: 3,
    heading: "Gifts for Sister :",
    links: ["Gifts for Friend", "Gifts for Couples"],
  },
  {
    id: 4,
    heading: "Gifts by Category :",
    links: [
      "Personalized Gifts",
      "Corporate Gifts",
      "Home & Living Gifts",
      "Fashion Lifestyle Gifts",
    ],
  },
  {
    id: 5,
    heading: "Gift ideas by Festivals/Occasions :",
    links: [
      "Mother's Day",
      "Father's Day",
      "Parents Day Gifts",
      "Friendship Day",
      "Raksha Bandhan",
      "Teacher's Day",
      "Grandparents Day",
      "Daughter's Day Gifts",
      "Boss Day",
      "Diwali",
      "Christmas",
      "New Year",
      "Valentine's Day",
      "Holi",
      "Women's Day",
    ],
  },
  {
    id: 6,
    heading: "Gift ideas by Special Occasions :",
    links: [
      "Birthday",
      "Anniversary",
      "Wedding",
      "Housewarming",
      "Best Wishes",
      "Gifts Under ₹99 - New",
    ],
  },
  {
    id: 7,
    heading: "Send Gifts to India :",
    links: [
      "Online Gift Delivery Mumbai",
      "Online Gift Delivery Delhi",
      "Online Gift Delivery Bangalore",
      "Online Gift Delivery Chennai",
      "Online Gift Delivery Hyderabad",
      "Online Gift Delivery Kolkata",
      "Pune Online Gifts",
      "Gurgaon Online Gifts",
      "Send Gifts to Noida",
    ],
  },
];
