const ratingData = [
  {
    id: 1,
    name: "Geeta Srinivas",
    rating: 4,
    date: "09-02-26",
    dateIndex: 1,
    comment: "Very nice canvas, love the result",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 2,
    name: "Ramesh Patil",
    rating: 1,
    date: "09-02-26",
    dateIndex: 2,
    comment: "Poor quality, colors faded quickly",
    recommend: 2,
    wouldByAgain: 2,
  },
  {
    id: 3,
    name: "Smita Venkatesh",
    rating: 5,
    date: "08-02-26",
    dateIndex: 3,
    comment: "Amazing canvas, colors are vivid",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 4,
    name: "Pankaj Kohli",
    rating: 4,
    date: "08-02-26",
    dateIndex: 4,
    comment: "Good quality work, satisfied customer",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 5,
    name: "Shweta Chauhan",
    rating: 5,
    date: "07-02-26",
    dateIndex: 5,
    comment: "Excellent print quality, loved it",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 6,
    name: "Vishal Dubey",
    rating: 4,
    date: "07-02-26",
    dateIndex: 6,
    comment: "Really good canvas, happy with it",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 7,
    name: "Bharti Sengupta",
    rating: 3,
    date: "06-02-26",
    dateIndex: 7,
    comment: "Nice quality, good for the price",
    recommend: 2,
    wouldByAgain: 3,
  },
  {
    id: 8,
    name: "Ashok Tiwari",
    rating: 5,
    date: "06-02-26",
    dateIndex: 8,
    comment: "Perfect canvas print, very satisfied",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 9,
    name: "Madhuri Goswami",
    rating: 4,
    date: "05-02-26",
    dateIndex: 9,
    comment: "Good product, well packaged",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 10,
    name: "Sunil Dutta",
    rating: 5,
    date: "05-02-26",
    dateIndex: 10,
    comment: "Loved the canvas, great quality",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 11,
    name: "Pallavi Rane",
    rating: 4,
    date: "04-02-26",
    dateIndex: 11,
    comment: "Impressive quality, looks amazing",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 12,
    name: "Naveen Kumar",
    rating: 3,
    date: "04-02-26",
    dateIndex: 12,
    comment: "Good canvas print, happy overall",
    recommend: 2,
    wouldByAgain: 3,
  },
  {
    id: 13,
    name: "Lakshmi Krishnan",
    rating: 5,
    date: "03-02-26",
    dateIndex: 13,
    comment: "Outstanding quality, perfect gift",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 14,
    name: "Mohan Das",
    rating: 4,
    date: "03-02-26",
    dateIndex: 14,
    comment: "Very good quality, fast shipping",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 15,
    name: "Preeti Tripathi",
    rating: 5,
    date: "02-02-26",
    dateIndex: 15,
    comment: "Beautiful work, love the finish",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 16,
    name: "Suresh Yadav",
    rating: 4,
    date: "02-02-26",
    dateIndex: 16,
    comment: "Nice canvas, colors are bright",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 17,
    name: "Ananya Dixit",
    rating: 3,
    date: "01-02-26",
    dateIndex: 17,
    comment: "Satisfied with quality, good service",
    recommend: 2,
    wouldByAgain: 3,
  },
  {
    id: 18,
    name: "Harish Kapoor",
    rating: 5,
    date: "01-02-26",
    dateIndex: 18,
    comment: "Excellent canvas quality, very pleased",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 19,
    name: "Ritu Arora",
    rating: 4,
    date: "31-01-26",
    dateIndex: 19,
    comment: "Good quality print, love it",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 20,
    name: "Gaurav Bhatt",
    rating: 5,
    date: "31-01-26",
    dateIndex: 20,
    comment: "Fantastic product, highly recommend",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 21,
    name: "Swati Jain",
    rating: 4,
    date: "30-01-26",
    dateIndex: 21,
    comment: "Great quality canvas, happy customer",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 22,
    name: "Rajesh Menon",
    rating: 3,
    date: "30-01-26",
    dateIndex: 22,
    comment: "Nice product, delivery was on time",
    recommend: 2,
    wouldByAgain: 3,
  },
  {
    id: 23,
    name: "Nisha Thakur",
    rating: 5,
    date: "29-01-26",
    dateIndex: 23,
    comment: "Superb quality, exceeded my expectations",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 24,
    name: "Akash Shetty",
    rating: 4,
    date: "29-01-26",
    dateIndex: 24,
    comment: "Very satisfied, good print resolution",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 25,
    name: "Ishita Pandey",
    rating: 5,
    date: "28-01-26",
    dateIndex: 25,
    comment: "Amazing canvas, looks stunning",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 26,
    name: "Vivek Saxena",
    rating: 4,
    date: "28-01-26",
    dateIndex: 26,
    comment: "Good experience, quality is nice",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 27,
    name: "Tanvi Agarwal",
    rating: 2,
    date: "27-01-26",
    dateIndex: 27,
    comment: "Average quality, packaging could be better",
    recommend: 2,
    wouldByAgain: 2,
  },
  {
    id: 28,
    name: "Sanjay Banerjee",
    rating: 5,
    date: "27-01-26",
    dateIndex: 28,
    comment: "Perfect quality, colors are accurate",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 29,
    name: "Megha Kulkarni",
    rating: 4,
    date: "26-01-26",
    dateIndex: 29,
    comment: "Really good quality, worth the price",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 30,
    name: "Nitin Shah",
    rating: 5,
    date: "26-01-26",
    dateIndex: 30,
    comment: "Excellent work, very impressed",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 31,
    name: "Divya Srinivasan",
    rating: 4,
    date: "25-01-26",
    dateIndex: 31,
    comment: "Nice canvas quality, prompt delivery",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 32,
    name: "Aditya Bose",
    rating: 3,
    date: "25-01-26",
    dateIndex: 32,
    comment: "Good product, meets expectations",
    recommend: 2,
    wouldByAgain: 3,
  },
  {
    id: 33,
    name: "Shalini Mishra",
    rating: 5,
    date: "24-01-26",
    dateIndex: 33,
    comment: "Beautiful print, great customer service",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 34,
    name: "Deepak Iyer",
    rating: 4,
    date: "24-01-26",
    dateIndex: 34,
    comment: "Good quality material, nice finish",
    recommend: 2,
    wouldByAgain: 3,
  },
  {
    id: 35,
    name: "Manish Pillai",
    rating: 4,
    date: "23-01-26",
    dateIndex: 35,
    comment: "Happy with the purchase, looks professional",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 36,
    name: "Riya Chopra",
    rating: 5,
    date: "23-01-26",
    dateIndex: 36,
    comment: "Loved it, perfect for my living room",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 37,
    name: "Pooja Desai",
    rating: 3,
    date: "22-01-26",
    dateIndex: 37,
    comment: "Nice canvas, good for home decor",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 38,
    name: "Karan Malhotra",
    rating: 5,
    date: "22-01-26",
    dateIndex: 38,
    comment: "Outstanding quality, will order again",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 39,
    name: "Simran Kaur",
    rating: 4,
    date: "21-01-26",
    dateIndex: 39,
    comment: "Great product, smooth ordering process",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 40,
    name: "Arjun Rao",
    rating: 5,
    date: "21-01-26",
    dateIndex: 40,
    comment: "Exceptional work, colors are vibrant",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 41,
    name: "Kavita Nair",
    rating: 4,
    date: "20-01-26",
    dateIndex: 41,
    comment: "Very nice quality, quick service",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 42,
    name: "Rohit Joshi",
    rating: 3,
    date: "20-01-26",
    dateIndex: 42,
    comment: "Satisfied with the product, good value",
    recommend: 2,
    wouldByAgain: 3,
  },
  {
    id: 43,
    name: "Anjali Mehta",
    rating: 5,
    date: "19-01-26",
    dateIndex: 43,
    comment: "Beautiful canvas, exceeded expectations",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 44,
    name: "Vikram Reddy",
    rating: 4,
    date: "19-01-26",
    dateIndex: 44,
    comment: "Good print quality and packaging",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 45,
    name: "Neha Gupta",
    rating: 5,
    date: "18-01-26",
    dateIndex: 45,
    comment: "Perfect gift, loved by everyone",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 46,
    name: "Amit Singh",
    rating: 4,
    date: "18-01-26",
    dateIndex: 46,
    comment: "Nice canvas quality, looks great on my wall",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 47,
    name: "Sneha Patel",
    rating: 3,
    date: "17-01-26",
    dateIndex: 47,
    comment: "Good experience overall, colors look nice",
    recommend: 2,
    wouldByAgain: 3,
  },
  {
    id: 48,
    name: "Rahul Verma",
    rating: 5,
    date: "17-01-26",
    dateIndex: 48,
    comment: "Amazing service, highly recommended",
    recommend: 4,
    wouldByAgain: 3,
  },
  {
    id: 49,
    name: "Priya Sharma",
    rating: 4,
    date: "16-01-26",
    dateIndex: 49,
    comment: "Good quality and fast delivery",
    recommend: 3,
    wouldByAgain: 4,
  },
  {
    id: 50,
    name: "Abhishek Kumar",
    rating: 5,
    date: "15-01-26",
    dateIndex: 50,
    comment: "Excellent quality prints, very happy with the result",
    recommend: 4,
    wouldByAgain: 4,
  },
  {
    id: 51,
    name: "Vikrant Joshi",
    rating: 1,
    date: "14-01-26",
    dateIndex: 51,
    comment: "Very disappointed with quality and durability",
    recommend: 2,
    wouldByAgain: 2,
  },
  {
    id: 52,
    name: "Priya Desai",
    rating: 2,
    date: "13-01-26",
    dateIndex: 52,
    comment: "Below expectations, some printing issues",
    recommend: 2,
    wouldByAgain: 2,
  },
];

export default ratingData;
